name: Validate Query and Answers

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
       ref: develop/2
    - name: Create Ontology Documentation 🔧
      run: |
         sudo apt-get install python3 python3-setuptools -y
         sudo apt-get install gcc libpq-dev -y
         sudo apt-get install python-dev -y
         sudo apt-get install python3-dev python3-pip python3-venv python3-wheel -y
         sudo pip3 install wheel pylode rdflib sparqlwrapper
         cd system
         python3 validatexml.py
